### ISSUE TITLE
TimeSeriesData example not working 

### ISSUE THREAD

**Issue by NHuxoll** [eclipse-basyx/basyx-applications#112]
Hi,
I was trying to run the [TimeSeriesData](https://github.com/eclipse-basyx/basyx-applications/tree/main/aas-gui/examples/TimeSeriesData) example. I cloned the repository and according to the README I just used ` docker compose up`.
Below I will provide some screenshots and log data. 

When opening the GUI on localhost:3000/ the first thing greeting is 
![Screenshot from 2024-04-10 12-02-05](https://github.com/eclipse-basyx/basyx-applications/assets/18661758/e0a94bfa-84e8-4600-8fcd-896bfabb15bd)

Furthermore no env setting from the docker-compose.yaml was used like the links for the SM Repo or AAS Registry
![Screenshot from 2024-04-10 12-02-15](https://github.com/eclipse-basyx/basyx-applications/assets/18661758/8f5e6902-39fc-42a6-b672-40902dd5516f)
``` yaml
  86   │   # AAS Web UI
  87   │   aas-ui:
  88   │     image: eclipsebasyx/aas-gui:v2-240125
  89   │     container_name: aas-ui
  90   │     ports:
  91   │       - "3000:3000"
  92   │     environment:
  93   │       VITE_AAS_REGISTRY_PATH: "http://localhost:8082"
  94   │       VITE_SUBMODEL_REGISTRY_PATH: "http://localhost:8083"
  95   │       VITE_AAS_REPO_PATH: "http://localhost:8081/shells"
  96   │       VITE_SUBMODEL_REPO_PATH: "http://localhost:8081/submodels"
  97   │       VITE_CD_REPO_PATH: "http://localhost:8081/concept-descriptions"
  98   │       VITE_PRIMARY_COLOR: "#76b900"
  99   │     volumes:
 100   │       - ./logo:/app/src/assets/Logo
 101   │     restart: always
``` 

And the AAS Environment is throwing some error:

``` bash
WARN[0000] $HOME/Git/Work/basyx/basyx-applications/aas-gui/examples/TimeSeriesData/docker-compose.yaml: `version` is obsolete
aas-environment  | Loaded property file: file:application.properties
aas-environment  | Loaded property file: jar:file:/application/basyxExecutable.jar!/BOOT-INF/classes!/application.properties
aas-environment  |   ____           _____
aas-environment  |  |  _ \         / ____|
aas-environment  |  | |_) |  __ _ | (___   _   _ __  __
aas-environment  |  |  _ <  / _` | \___ \ | | | |\ \/ /
aas-environment  |  | |_) || (_| | ____) || |_| | >  <
aas-environment  |  |____/  \__,_||_____/  \__, |/_/\_\
aas-environment  | ======================== __/ |======
aas-environment  | AAS Environment         |___/
aas-environment  | 2.0.0-PREVIEW
aas-environment  |
aas-environment  | 2024-04-10T09:17:13.753Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : Starting AasEnvironmentComponent v2.0.0-SNAPSHOT using Java 17.0.10 with PID 1 (/application/basyxExecutable.jar started by nobody in /application)
aas-environment  | 2024-04-10T09:17:13.756Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentComponent      : No active profile set, falling back to 1 default profile: "default"
aas-environment  | 2024-04-10T09:17:15.397Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
aas-environment  | 2024-04-10T09:17:15.407Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 7 ms. Found 0 MongoDB repository interfaces.
aas-environment  | 2024-04-10T09:17:15.453Z  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
aas-environment  | 2024-04-10T09:17:15.465Z  INFO 1 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
aas-environment  | 2024-04-10T09:17:16.097Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
aas-environment  | 2024-04-10T09:17:16.109Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
aas-environment  | 2024-04-10T09:17:16.110Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.13]
aas-environment  | 2024-04-10T09:17:16.194Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
aas-environment  | 2024-04-10T09:17:16.195Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2387 ms
aas-environment  | 2024-04-10T09:17:16.436Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -------------------- Aas Environment Features: --------------------
aas-environment  | 2024-04-10T09:17:16.436Z  INFO 1 --- [           main] o.e.d.b.a.c.AasEnvironmentFeaturePrinter : -----------------------------------------------------------------
aas-environment  | 2024-04-10T09:17:18.393Z  INFO 1 --- [           main] a.p.AasEnvironmentPreconfigurationLoader : Scanning for preconfigured AAS Environments
aas-environment  | 2024-04-10T09:17:18.401Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: java.nio.file.AccessDeniedException: aas/aasx
aas-environment  | 2024-04-10T09:17:18.404Z  WARN 1 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Invocation of close method failed on bean with name 'mqttClient': Client is connected (32100)
aas-environment  | 2024-04-10T09:17:18.408Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
aas-environment  | 2024-04-10T09:17:18.436Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :
aas-environment  |
aas-environment  | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
aas-environment  | 2024-04-10T09:17:18.463Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
aas-environment  |
aas-environment  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'preconfigurationLoaderInitializer' defined in URL [jar:file:/application/basyxExecutable.jar!/BOOT-INF/lib/basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/org/eclipse/digitaltwin/basyx/aasenvironment/preconfiguration/PreconfigurationLoaderInitializer.class]: java.nio.file.AccessDeniedException: aas/aasx
aas-environment  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.4.jar!/:3.1.4]
aas-environment  |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-3.1.4.jar!/:3.1.4]
aas-environment  |      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.1.4.jar!/:3.1.4]
aas-environment  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.1.4.jar!/:3.1.4]
aas-environment  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar!/:3.1.4]
aas-environment  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar!/:3.1.4]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.component.AasEnvironmentComponent.main(AasEnvironmentComponent.java:42) ~[classes!/:2.0.0-SNAPSHOT]
aas-environment  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
aas-environment  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
aas-environment  |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
aas-environment  |      at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
aas-environment  |      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-environment  |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-environment  |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-environment  |      at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[basyxExecutable.jar:2.0.0-SNAPSHOT]
aas-environment  | Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: aas/aasx
aas-environment  |      at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87) ~[na:na]
aas-environment  |      at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103) ~[na:na]
aas-environment  |      at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132) ~[na:na]
aas-environment  |      at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[na:na]
aas-environment  |      at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
aas-environment  |      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
aas-environment  |      at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[na:na]
aas-environment  |      at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:na]
aas-environment  |      at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[na:na]
aas-environment  |      at org.springframework.integration.file.RecursiveDirectoryScanner.listFiles(RecursiveDirectoryScanner.java:84) ~[spring-integration-file-6.1.3.jar!/:6.1.3]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.extractFilesToLoadFromEnvironmentDirectory(AasEnvironmentPreconfigurationLoader.java:127) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.resolvePathAndAddFilesToList(AasEnvironmentPreconfigurationLoader.java:110) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.resolveFiles(AasEnvironmentPreconfigurationLoader.java:103) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.scanForEnvironments(AasEnvironmentPreconfigurationLoader.java:92) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.AasEnvironmentPreconfigurationLoader.loadPreconfiguredEnvironments(AasEnvironmentPreconfigurationLoader.java:75) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.loadPreconfiguredEnvironment(PreconfigurationLoaderInitializer.java:68) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.eclipse.digitaltwin.basyx.aasenvironment.preconfiguration.PreconfigurationLoaderInitializer.afterPropertiesSet(PreconfigurationLoaderInitializer.java:60) ~[basyx.aasenvironment-core-2.0.0-SNAPSHOT.jar!/:2.0.0-SNAPSHOT]
aas-environment  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.12.jar!/:6.0.12]
aas-environment  |      ... 24 common frames omitted
aas-environment  | Caused by: java.nio.file.AccessDeniedException: aas/aasx
aas-environment  |      at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
aas-environment  |      at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
aas-environment  |      at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
aas-environment  |      at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:440) ~[na:na]
aas-environment  |      at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482) ~[na:na]
aas-environment  |      at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:301) ~[na:na]
aas-environment  |      at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374) ~[na:na]
aas-environment  |      at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83) ~[na:na]
aas-environment  |      ... 42 common frames omitted
aas-environment  | 

```

**Comment by aaronzi** [comment]
Thank you for raising this issue @NHuxoll.

Looks like a permission problem when reading the Asset Administration Shells from the mounted "aas" folder. The shown error in the UI is caused by the AAS Environment not running. Maybe the aas-env container is not allowed to read files from your computer. @FrankSchnicke, have you encountered this problem before? Do you have an idea what could cause this issue?

**Comment by FrankSchnicke** [comment]
Did you modify the example? I see that BaSyx is trying to load the _aas/aasx_ folder which does not exist in the original example.

**Comment by NHuxoll** [comment]
I removed everything and cloned it again, so it could have been some kind of permission issue on my side.
Now the Environment is not throwing any errors anymore but there is no SM Registry or demo available.

Is there also somewhere the code to generate the AASX file for this example?

![Screenshot from 2024-04-11 09-01-58](https://github.com/eclipse-basyx/basyx-applications/assets/18661758/4e841b22-43bf-457c-971c-cf20c881c6f7)

**Comment by aaronzi** [comment]
Can you try to enter the registry values manually?

AAS Registry URL: `http://localhost:8082`
Submodel Registry URL: `http://localhost:8083`

What do you mean by "Is there also somewhere the code to generate the AASX file for this example?"?
This example was not created from code. I created the .aasx file in a tool called AAS Suite (from Metalevel AG).

**Comment by NHuxoll** [comment]
I tried it manually and got an error.

And thanks for the info, I thought it was maybe created with the python or Java SDK

![Screenshot from 2024-04-11 09-21-43](https://github.com/eclipse-basyx/basyx-applications/assets/18661758/66aabdfb-87ce-43c1-b19f-091e36d88b6c)

**Comment by aaronzi** [comment]
Can you open the browser dev-tools and send me a screenshot from the console and network tab?

**Comment by aaronzi** [comment]
I tried to run the example myself. I see the problem now. There was an update on how to configure the registries (after this example was created). Normally that would not be a problem if a new image had been created in DockerHub. In this case, the old image which the example ran on was overwritten. Now the configuration of the example is not working anymore with the images of the registries used here.

I will have to update the configuration of this example. Sorry for this oversight. Can you tell me how urgently you need this example to run? Would May be enough for you?
