### ISSUE TITLE
Unable to open .aasx file which is created by using SAMM CLI

### ISSUE THREAD

**Issue by Punith-Arumilli** [eclipse-basyx/basyx-applications#50]
Hi, 
I created Aspect Model and I converted it into Asset Administration Shell using SAMM CLI. Now if I am trying to open it using AASX Package Explorer it is showing an error.  

Loading aasx file repository ..\..\..\..\..\Sample_AAS\aasxrepo-new.json ..
File not found when loading aasx file repository ..\..\..\..\..\Sample_AAS\aasxrepo-new.json
Application started ..
[AasxPluginAdvancedTextEditor] ListActions() called
[AasxPluginAdvancedTextEditor] InitPlugin() called with args = 
[AasxPluginBomStructure] ListActions() called
[AasxPluginBomStructure] InitPlugin() called with args = 
[AasxPluginDocumentShelf] InitPlugin() called with args = 
[AasxPluginExportTable] ListActions() called
[AasxPluginExportTable] InitPlugin() called with args = 
[AasxPluginGenericForms] ListActions() called
[AasxPluginGenericForms] InitPlugin() called with args = 
[AasxPluginImageMap] ListActions() called
[AasxPluginImageMap] InitPlugin() called with args = 
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginMtpViewer] ListActions() called
[AasxPluginMtpViewer] InitPlugin() called with args = 
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginPlotting] ListActions() called
[AasxPluginPlotting] InitPlugin() called with args = 
[AasxPluginSmdExporter] ListActions() called
[AasxPluginSmdExporter] InitPlugin() called with args = 
[AasxPluginTechnicalData] ListActions() called
[AasxPluginTechnicalData] InitPlugin() called with args = 
[AasxPluginOpcUaClient] ListActions() called
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginUaNetServer] ListActions() called
[AasxPluginUaNetServer] InitPlugin() called with args = 
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginWebBrowser] ListActions() called
[AasxPluginWebBrowser] InitPlugin() called with args = 
Loading new AASX from: C:\Users\punit\Downloads\MeasurementUnit.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\punit\AppData\Local\Temp\tmp905C.aasx from source local file: C:\Users\punit\Downloads\MeasurementUnit.aasx buffered to: C:\Users\punit\AppData\Local\Temp\tmp905C.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\punit\AppData\Local\Temp\tmp905C.aasx at \AdminShellPackageEnv.cs:line 313 gave: Part URI must start with a forward slash. at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
    Stacktrace:    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Loading new AASX from: C:\Users\punit\Downloads\Universal_Robot.aasx as auxiliary False ..
AASX C:\Users\punit\Downloads\Universal_Robot.aasx loaded.
[AasxPluginExportTable] Export UML data to file: C:\Users\punit\Desktop\new.uml
[AasxPluginExportTable] Export UML data copied to paste buffer.
[AasxPluginExportTable] Export UML data to file: C:\Users\punit\Downloads\new.xml
[AasxPluginExportTable] Export UML data copied to paste buffer.
[AasxPluginExportTable] Exporting table: C:\Users\punit\Downloads\new.docx
Loading new AASX from: C:\Users\punit\Downloads\MeasurementUnit.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\punit\AppData\Local\Temp\tmp475F.aasx from source local file: C:\Users\punit\Downloads\MeasurementUnit.aasx buffered to: C:\Users\punit\AppData\Local\Temp\tmp475F.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\punit\AppData\Local\Temp\tmp475F.aasx at \AdminShellPackageEnv.cs:line 313 gave: Part URI must start with a forward slash. at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
    Stacktrace:    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aaronzi** [comment]
Hello @Punith-Arumilli,
it looks like you placed this issue in the wrong repository.
This seems to be more related to the AASX Package Explorer and not the BaSyx Applications.
I would suggest moving your issue here: https://github.com/eclipse-aaspe/aaspe

**Comment by Punith-Arumilli** [comment]
Tried to open it using basyxs aas server but here also i am encountering errors

C:\MUAAS>docker run --name=aas -p 8081:4001 -v %cd%/aasServer:/usr/share/config eclipsebasyx/aas-server:1.5.0
17:51:43.390 [main] INFO org.eclipse.basyx.components.aas.executable.AASServerExecutable -- Starting BaSyx AASServer component...
17:51:43.397 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Loading properties from file '/usr/share/config/context.properties'
17:51:43.397 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Loading from inputStream: java.io.FileInputStream@2344fc66
17:51:43.398 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - contextHostname: 'localhost'
17:51:43.398 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - contextPath: '/aasServer'
17:51:43.398 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - contextPort: '4001'
17:51:43.410 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Loading properties from file '/usr/share/config/aas.properties'
17:51:43.410 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Loading from inputStream: java.io.FileInputStream@36d4b5c
17:51:43.411 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - aas.aasxUpload: 'Enabled'
17:51:43.411 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - aas.backend: 'InMemory'
17:51:43.411 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - aas.events: 'NONE'
17:51:43.411 [main] INFO org.eclipse.basyx.components.configuration.BaSyxConfiguration -- Property File - aas.source: '/usr/share/config/MeasurementUnit.aasx'
17:51:43.436 [main] INFO org.eclipse.basyx.components.aas.AASServerComponent -- Create the server...
17:51:43.465 [main] INFO org.eclipse.basyx.components.aas.AASServerComponent -- Loading aas from aasx "/usr/share/config/MeasurementUnit.aasx"
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.HashMap.putMapEntries(HashMap.java:497)
        at java.base/java.util.HashMap.putAll(HashMap.java:781)
        at org.eclipse.basyx.aas.factory.xml.XMLToMetamodelConverter.<init>(XMLToMetamodelConverter.java:69)
        at org.eclipse.basyx.aas.factory.aasx.AASXToMetamodelConverter.retrieveAasEnv(AASXToMetamodelConverter.java:122)
        at org.eclipse.basyx.aas.factory.aasx.AASXToMetamodelConverter.retrieveAASBundles(AASXToMetamodelConverter.java:139)
        at org.eclipse.basyx.aas.factory.aasx.AASXToMetamodelConverter.parseReferencedFilePathsFromAASX(AASXToMetamodelConverter.java:243)
        at org.eclipse.basyx.aas.factory.aasx.AASXToMetamodelConverter.unzipRelatedFiles(AASXToMetamodelConverter.java:320)
        at org.eclipse.basyx.aas.factory.aasx.AASXToMetamodelConverter.unzipRelatedFilesToChildPath(AASXToMetamodelConverter.java:306)
        at org.eclipse.basyx.components.aas.AASServerComponent.loadBundleFromAASX(AASServerComponent.java:564)
        at org.eclipse.basyx.components.aas.AASServerComponent.loadBundleFromFile(AASServerComponent.java:670)
        at org.eclipse.basyx.components.aas.AASServerComponent.loadAASFromSource(AASServerComponent.java:656)
        at org.eclipse.basyx.components.aas.AASServerComponent.loadAASBundles(AASServerComponent.java:643)
        at org.eclipse.basyx.components.aas.AASServerComponent.createAggregatorServlet(AASServerComponent.java:588)
        at org.eclipse.basyx.components.aas.AASServerComponent.startComponent(AASServerComponent.java:256)
        at org.eclipse.basyx.components.aas.executable.AASServerExecutable.main(AASServerExecutable.java:66)

**Comment by aaronzi** [comment]
Alright, do you know the version of the AAS metamodel your AASX file has? I suspect that you are probably using the wrong version of the BaSyx components respectively the wrong version of the AASX package explorer.

Could you supply your AASX file so that I can check if the file itself is compliant with the AAS metamodel?

**Comment by FrankSchnicke** [comment]
I guess you're using meta model V3, right? For this, please use the components documented here:
https://github.com/eclipse-basyx/basyx-java-server-sdk

**Comment by Punith-Arumilli** [comment]
Here is the AASX file 
[MeasurementUnit.zip](https://github.com/eclipse-basyx/basyx-applications/files/13884643/MeasurementUnit.zip)

**Comment by abhishekmaha23** [comment]
The AASX file itself has v3, but the command you're using 
`docker run --name=aas -p 8081:4001 -v %cd%/aasServer:/usr/share/config eclipsebasyx/aas-server:1.5.0`
seems to be for the previous version of Basyx, which was compatible with AAS v2

I believe some of the applications in this repository are not yet updated to the latest version of Baysx (but the Package Explorer is).

You might need to use an older version of the AASX Package Explorer (that exports to AAS v2 AASX files), if I'm not mistaken.

**Comment by aaronzi** [comment]
You are right @abhishekmaha23, only the AAS UI supports v3 in this repository. But as @FrankSchnicke already said, please use the new version of BaSyx (v2) to host your specific AAS. An example on how to do that can be found here: https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples

**Comment by FrankSchnicke** [comment]
This is related to a compatibility issue with AASX Package Explorer. For further details, see https://github.com/admin-shell-io/aasx-package-explorer/issues/654 - I contributed a patch that will be included in the next version of the AASX Package Explorer. Afterwards, it will be possible to load the AASX files created by BaSyx in the AASX Package Explorer.

Since this is not related to BaSyx itself, I will close this ticket.
